# Default values for chatgpt-backend-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
defaultLabel: chatgpt-backend
defaultNamespace: chatgpt

image:
  repository: uj5ghare/chatgpt-backend
  pullPolicy: Always
  tag: "1.37.1"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  className: nginx
  host: chatgpt-backend.local

autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

