name: CI/CD Pipeline

on:
  push:
    branches:
      - nikhil  # Trigger the workflow on pushes to the 'nikhil' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy Docker Compose file to EC2
      run: scp -o StrictHostKeyChecking=no -r docker-compose.yml ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/your_project_directory/

    - name: Copy backend files to EC2
      run: scp -o StrictHostKeyChecking=no -r backend ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/your_project_directory/

    - name: Copy frontend files to EC2
      run: scp -o StrictHostKeyChecking=no -r frontend ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/your_project_directory/

    - name: Deploy on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd ~/your_project_directory
          docker-compose down
          docker-compose up -d --build
        EOF
